version: "3.9"
services:
  osaka:
    build:
      context: .
      DockerFile: DockerFile.dev
    ports:
      -"3001:3001"
    links:
      - postl
    volumes:
      - .:/home/app
  postl:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=jona
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data: