version: "3.9"
services:
  osaka:
    build: .
    ports:
      - "3001:3001"
    links:
      - postl
  postl:
    image: postgres:14.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jona
      - POSTGRES_PASSWORD=password
