version: "3.9"
services:
  osaka:
    build: .
    ports:
      - "3001:3001"
    links:
      - postl
  postl:
    image: postgres:14.0
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD=password
    volumes:
      - PGDATA:/var/lib/postgresql/data

volumes:
  PGDATA: